CREATE TABLE IF NOT EXISTS categories
(
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    category VARCHAR(64) COLLATE pg_catalog."default" NOT NULL,
    image_path TEXT COLLATE pg_catalog."default" NOT NULL,
    slug VARCHAR(64) COLLATE pg_catalog."default",
    CONSTRAINT categories_pkey PRIMARY KEY (id)
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS categories
    OWNER TO postgres;

CREATE TABLE IF NOT EXISTS products
(
    article_number INTEGER NOT NULL,
    kcal INTEGER NOT NULL,
    price INTEGER NOT NULL,
    weight INTEGER NOT NULL,
    category_id BIGINT,
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    title VARCHAR(64) COLLATE pg_catalog."default" NOT NULL,
    compound VARCHAR(255) COLLATE pg_catalog."default",
    description VARCHAR(255) COLLATE pg_catalog."default",
    image_path VARCHAR(255) COLLATE pg_catalog."default",
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT category_id_fk FOREIGN KEY (category_id)
        REFERENCES categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS products
    OWNER TO postgres;
