version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8081:8081"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mosweet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=nata155630
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:12.22'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nata155630
    ports:
      - "5432:5432"
#  redis:
#    image: 'redis:latest'
#    container_name: 'redis'
#    restart: always
#    ports:
#      - "6369:6369"